import json
from fp2a_qe2qeJson import isNonStandardSectionTitle

def keywordsValuePackaging(keyword):

    # datatype converter
    if type(keyword) == str:
        return keyword
    elif type(keyword) == bool:
        return str(int(keyword))
    else:
        try:
            return str(keyword)
        except ValueError:
            raise ValueError('ERROR: ' + keyword + ' is not a valid value for keyword ' + keyword)

def discrepantConversion(keyword, value):
    if keyword == 'calculation':
        if value == 'scf' or value == 'relax' or value == 'nscf' or value == 'md':
            return value
        elif value == 'vc-relax':
            return 'cell-relax'        
        else:
            print('WARNING: ' + value + ' is not a valid value for keyword ' + keyword + ', using default value')
            return 'scf'
    else:
        return value

def hubbardManifoldToNumber(manifold):
    if manifold == 'unknown_manifold_from_old_qe_versions':
        print('WARNING: no information for determining the angular momentum of the element, assuming disabled')
        return '-1'
    elif manifold[-1] == 's':
        return '0'
    elif manifold[-1] == 'p':
        return '1'
    elif manifold[-1] == 'd':
        return '2'
    elif manifold[-1] == 'f':
        return '3'
    elif manifold[-1] == 'g':
        return '4'
    elif manifold[-1] == 'h':
        return '5'
    else:
        # are you serious you are using such a high angular momentum?
        return '-1'

def fromElementFindLinesInXYZ(element, elementListInXYZ):

    lines = []
    for i in range(len(elementListInXYZ)):
        if elementListInXYZ[i] == element:
            lines.append(i)
    return lines

def generateABACUSFiles(
    mode = 'on-the-fly',
    qeInputScriptJson = None,
    qeInputScriptJsonFile = 'qeInputScript.json', 
    keywordConversionJson = None,
    keywordConversionJsonFile = 'keywordConversion.json', 
    ABACUSInputFile = 'INPUT', 
    ABACUSStructureFile = 'STRU', 
    ABACUSKpointsFile = 'KPT',
    qeVersion_7_1 = True,
    overwriteKeywords = {},
    additionalKeywords = {},
    boolUpdateInformation = False
    ):

    """
    # generate ABACUS input files from QE input script in json format\n
    @param mode: the mode controlling how to read dictionary data, available choices are on-the-fly and file\n
    @param qeInputScriptJsonFile: QE input script in json format generated by qe2qeJson.py\n
    @param keywordConversionJsonFile: json file containing the conversion table of QE keywords to ABACUS keywords,
    generated by jsonRotation.py\n
    @param ABACUSInputFile: ABACUS input file name, default is INPUT\n
    @param ABACUSStructureFile: ABACUS structure file name, default is STRU\n
    @param ABACUSKpointsFile: ABACUS kpoints file name, default is KPT\n
    @param qeVersion_7_1: whether the QE version is >= 7.1, default is True\n
    @param overwriteKeywords: keywords to be overwritten, default is empty\n
    @param additionalKeywords: additional keywords to be added to the ABACUS input file, default is empty
    """
    qeNonstandardSections = []

    if mode == 'on-the-fly':
        if qeInputScriptJson == None:
            qeInputScript = {}
            raise Exception('qeInputScriptJson is not provided')
        if keywordConversionJson == None:
            keywordConversion = {}
            raise Exception('keywordConversionJson is not provided')
        else:
            qeInputScript = qeInputScriptJson
            keywordConversion = keywordConversionJson

    elif mode == 'file':
        with open(qeInputScriptJsonFile, 'r') as f:
            qeInputScript = json.load(f)
        with open(keywordConversionJsonFile, 'r') as f:
            keywordConversion = json.load(f)
    else:
        qeInputScript = {}
        keywordConversion = {}
        raise Exception('mode is not valid')

    with open(ABACUSInputFile, 'w') as f:
        f.writelines('INPUT_PARAMETERS\n')
        f.writelines('basis_type pw\n')
        if len(qeInputScript.keys()) == 0:
            raise Exception('QE input script is empty')

        for section in qeInputScript:

            if section == '__version__':
                if qeInputScript[section] == '>=7.1':
                    qeVersion_7_1 = True
                else:
                    qeVersion_7_1 = False
            elif isNonStandardSectionTitle(section):
                if section != 'CELL_PARAMETERS' and section != 'ATOMIC_POSITIONS' and section != 'K_POINTS' and section != 'ATOMIC_SPECIES':
                    qeNonstandardSections.append(section)
            else:
                for keyword in qeInputScript[section]:

                    if keyword in keywordConversion:
                        if boolUpdateInformation:
                            print('> original keyword: ' + keyword)
                            print('> converted keyword: ' + keywordConversion[keyword][0])
                            print('> pass its value: ' + str(qeInputScript[section][keyword]))
                        value = discrepantConversion(keyword, qeInputScript[section][keyword])
                        if keyword in overwriteKeywords.keys():
                            value = overwriteKeywords[keyword]
                        f.writelines(keywordConversion[keyword][0] + ' ' + keywordsValuePackaging(value) + '\n')
                        # subscript 0 is the position of abacus keyword in the list of values
                    else:
                        print('WARNING: Keyword ' + keyword + ' not found in conversion table')

        # proceeding non-standard section that unrevelant with STRU and KPT/KLINE files
        for section in qeNonstandardSections:
            if section == 'HUBBARD':
                # well I should say pw is not implemented with dft+u in abacus now...
                # maybe pw is not quite encouraged to be used in abacus? i don't know
                # but i set it here just in case
                if qeVersion_7_1:
                    # because for qe >= 7.1, enabling dft+u calculation is from defining HUBBARD section rather than lda_plus_u
                    # keyword, such keyword is deprecated in version >= 7.1
                    f.writelines('dft_plus_u 1\n')
                else:
                    pass
                
                manifoldCorrection = []
                hubbardUValues = []
                for element in qeInputScript['ATOMIC_SPECIES']['elements']:
                    # abacus also has not implement manifold-by-manifold scheme of dft+u, 
                    # so presently i just use the last one
                    try:
                        manifold = list(qeInputScript['HUBBARD']['on-site'][element].keys())[-1]
                        manifoldCorrection.append(hubbardManifoldToNumber(manifold))
                        hubbardUValues.append(
                            keywordsValuePackaging(
                                qeInputScript['HUBBARD']['on-site'][element][manifold]["U"]
                            )
                            )
                    except KeyError:
                        manifoldCorrection.append('-1')
                        hubbardUValues.append('0.0')
                orbital_corr = ' '.join(manifoldCorrection)
                f.writelines('orbital_corr ' + orbital_corr + '\n')
                hubbard_u = ' '.join(hubbardUValues)
                f.writelines('hubbard_u ' + hubbard_u + '\n')

            elif section == 'SOLVANTS':
                pass
            elif section == 'OCCUPATIONS':
                pass
        for keyword in additionalKeywords:
            f.writelines(keyword + ' ' + keywordsValuePackaging(additionalKeywords[keyword]) + '\n')

    with open(ABACUSStructureFile, 'w') as f:
        f.writelines('ATOMIC_SPECIES\n')
        for ityp in range(qeInputScript['system']['ntyp']):
            f.writelines(
                qeInputScript['ATOMIC_SPECIES']['elements'][ityp] 
                + ' ' 
                + keywordsValuePackaging(qeInputScript['ATOMIC_SPECIES']['masses'][ityp])
                + ' ' 
                + keywordsValuePackaging(qeInputScript['ATOMIC_SPECIES']['pseudopotentials'][ityp])
                + '\n')
        f.writelines('\nLATTICE_CONSTANT\n1.0\n')
        f.writelines('\nLATTICE_VECTORS\n')
        for cell_vector in qeInputScript['CELL_PARAMETERS']['cell']:
            f.writelines(
                keywordsValuePackaging(cell_vector[0]) + ' ' 
                + keywordsValuePackaging(cell_vector[1]) + ' ' 
                + keywordsValuePackaging(cell_vector[2]) + '\n')
        f.writelines('\nATOMIC_POSITIONS\nCartesian\n\n')
        for ityp in range(qeInputScript['system']['ntyp']):
            f.writelines(qeInputScript['ATOMIC_SPECIES']['elements'][ityp] + '\n')
            try:
                if qeInputScript['system']['nspin'] == 1:
                    f.writelines('0.0\n')
                else:
                    try:
                        f.writelines(keywordsValuePackaging(
                            qeInputScript['system']['starting_magnetization({})'.format(str(ityp))]
                            ) + '\n')
                    except KeyError:
                        f.writelines('0.0\n')
            except KeyError:
                f.writelines('0.0\n')
            lineIndices = fromElementFindLinesInXYZ(qeInputScript['ATOMIC_SPECIES']['elements'][ityp], qeInputScript['ATOMIC_POSITIONS']['elements'])
            f.writelines(str(len(lineIndices)) + '\n')
            for lineIndex in lineIndices:
                f.writelines(
                    keywordsValuePackaging(qeInputScript['ATOMIC_POSITIONS']['coordinates'][lineIndex][0])
                    + ' ' + keywordsValuePackaging(qeInputScript['ATOMIC_POSITIONS']['coordinates'][lineIndex][1])
                    + ' ' + keywordsValuePackaging(qeInputScript['ATOMIC_POSITIONS']['coordinates'][lineIndex][2])
                    + ' ')
                f.writelines(
                    keywordsValuePackaging(abs(qeInputScript['ATOMIC_POSITIONS']['constraints'][lineIndex][0]-1))
                    + ' ' + keywordsValuePackaging(abs(qeInputScript['ATOMIC_POSITIONS']['constraints'][lineIndex][1]-1))
                    + ' ' + keywordsValuePackaging(abs(qeInputScript['ATOMIC_POSITIONS']['constraints'][lineIndex][2]-1))
                    + '\n')
            f.writelines('\n')

    with open(ABACUSKpointsFile, 'w', encoding='utf-8') as f:

        f.writelines('K_POINTS\n')
        f.writelines('0\n')
        f.writelines('Gamma\n')
        if qeInputScript['K_POINTS']['mode'] == 'mk':
            f.writelines(
                keywordsValuePackaging(qeInputScript['K_POINTS']['grid'][0]) + ' '
                + keywordsValuePackaging(qeInputScript['K_POINTS']['grid'][1]) + ' '
                + keywordsValuePackaging(qeInputScript['K_POINTS']['grid'][2]) + ' '
                + keywordsValuePackaging(qeInputScript['K_POINTS']['shift'][0]) + ' '
                + keywordsValuePackaging(qeInputScript['K_POINTS']['shift'][1]) + ' '
                + keywordsValuePackaging(qeInputScript['K_POINTS']['shift'][2]) + '\n'
            )
        elif qeInputScript['K_POINTS']['mode'] == 'kpath':
            print('In this case you should make sure you already have a KPT file')
            with open('KLINES', 'w') as f2:
                f2.writelines('K_POINTS\n')
                f2.writelines(str(len(qeInputScript['K_POINTS']['kpts'])) + '\n')
                f2.writelines('Line\n')
                for i, kpt in enumerate(qeInputScript['K_POINTS']['kpts']):
                    f2.writelines(
                        keywordsValuePackaging(kpt[0]) + ' ' 
                        + keywordsValuePackaging(kpt[1]) + ' ' 
                        + keywordsValuePackaging(kpt[2]) + ' ' 
                        + keywordsValuePackaging(qeInputScript['K_POINTS']['w_kpts'][i] )
                        + '\n')
                f2.writelines('\n\n')

if __name__ == '__main__':
    
    generateABACUSFiles(
        mode = 'file',
        qeInputScriptJsonFile = "example13_run_example_0.json",
        keywordConversionJsonFile = "depuis_le_abacus_rotated-qac.json",
        qeVersion_7_1 = True
    )